language: python

python:
- "3.5"
- "3.6"
- "3.7"
- "3.8"
- "pypy3.5"

install:
- pip install .
- pip install python-coveralls coverage

script:
- coverage -m unittest discover

after_success:
- coveralls
